apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: '56512b4a01fc91026b0d42ba2febb1b61c291903'
  - name: appGitUrl
    value: 'git@github.com:ajoyacharyya/coffee-testing.git'
  - name: configGitUrl
    value: 'git@github.com:ajoyacharyya/coffee-testing-config.git'
  - name: appImage
    value: 'docker.ajoyacharyya.com/coffee-testing'
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
