apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  resources:
  - name: appImage
    resourceRef:
      name: coffee-testing-image
  - name: appSource
    resourceRef:
      name: coffee-testing-git-source
  - name: gitOpsSource
    resourceRef:
      name: gitops-git-source
  params:
  - name: buildRevision
    value: '2'
---
