apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
  - name: buildRevision
    description: The revision of the build
  resources:
  - name: appSource
    type: git
  - name: appImage
    type: image
  - name: gitOpsSource
    type: git
  workspaces:
  - name: maven-cache

  tasks:
  - name: build-java-app
    taskRef:
      name: build-java-app
    resources:
      inputs:
      - name: source
        resource: appSource
      outputs:
      - name: builtImage
        resource: appImage
    params:
    - name: buildRevision
      value: $(params.buildRevision)
    workspaces:
    - name: maven-cache
      workspace: maven-cache

  - name: deploy-systemtest
    taskRef:
      name: deploy
    runAfter:
    - build-java-app
    resources:
      inputs:
      - name: source
        resource: gitOpsSource
      - name: image
        resource: appImage
    params:
    - name: buildRevision
      value: $(params.buildRevision)
    - name: environment
      value: systemtest
    - name: argo-app-name
      value: coffee-testing-systemtest

  - name: run-systemtest
    taskRef:
      name: run-systemtest
    runAfter:
    - deploy-systemtest
    resources:
      inputs:
      - name: source
        resource: appSource
    params:
    - name: gateway
      value: '161.156.128.162'
    workspaces:
    - name: maven-cache
      workspace: maven-cache

  - name: deploy-prod
    taskRef:
      name: deploy
    runAfter:
    - run-systemtest
    resources:
      inputs:
      - name: source
        resource: gitOpsSource
      - name: image
        resource: appImage
    params:
    - name: buildRevision
      value: $(params.buildRevision)
    - name: environment
      value: production
    - name: argo-app-name
      value: coffee-testing-prod

  - name: run-prod-smoketest
    taskRef:
      name: run-smoketest
    runAfter:
    - deploy-prod
    resources:
      inputs:
      - name: source
        resource: appSource
    params:
    - name: gateway
      value: '161.156.128.162'
    workspaces:
    - name: maven-cache
      workspace: maven-cache
---
