apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-smoketest
spec:
  params:
  - name: gateway
  - name: buildRevision
  - name: appGitUrl
  workspaces:
  - name: app-source
  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "/workspace/app-source/"
    script: |
      #!/usr/bin/env sh
      set -e

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

      rm -rf ./* ./.[!.]* ./..?*
      git init
      git remote add origin $(params.appGitUrl)
      git fetch --depth 1 origin $(params.buildRevision)
      git checkout FETCH_HEAD

  - name: run-mvn-st
    image: sdaschner/maven-jdk14:quarkus-deps-1.5.1-b5
    workingDir: "/workspace/app-source/coffee-shop"
    command:
    - /usr/bin/mvn
    args:
    - test-compile
    - failsafe:integration-test
    - failsafe:verify
    - "-Dcoffee-shop.test.host=$(inputs.params.gateway)"
    - "-Dcoffee-shop.test.port=80"
    env:
    - name: MAVEN_OPTS
      value: "-Xms2G -Xmx4G"
    resources:
      requests:
        cpu: '2'
        memory: '4Gi'
---