apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-systemtest
spec:
  params:
  - name: gateway
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: run-mvn-st
    image: gcr.io/cloud-builders/mvn
    workingDir: "/workspace/source/coffee-shop/coffee-shop-st"
    command:
    - /usr/bin/mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-cache.path)
    - verify
    - "-Dcoffee-shop.test.host=$(inputs.params.gateway)"
    - "-Dcoffee-shop.test.port=80"
    - "-Dbarista.test.host=$(inputs.params.gateway)"
    - "-Dbarista.test.port=80"
---