apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: buildRevision
  resources:
    inputs:
    - name: image
      type: image
    - name: source
      type: git
  steps:
  - name: update-yaml
    image: alpine/git:v2.26.2
    #    image: mikefarah/yq:3.3.4
    #    command: ['yq', 'write', '-i', 'coffee-shop.yaml', '-d', '1', 'spec.template.spec.containers[0].image', "$(inputs.resources.image.url):$(inputs.params.buildRevision)"]
    workingDir: "/workspace/source/production/"
    script: |
      #!/usr/bin/env sh
      set -e

      echo "updating coffee-shop image to $(inputs.resources.image.url):$(inputs.params.buildRevision)"
      sed -i "s#$(inputs.resources.image.url):[a-zA-Z0-9]\\+#$(inputs.resources.image.url):$(inputs.params.buildRevision)#" coffee-shop.yaml

  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "/workspace/source/"
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "Tekton Pipeline"
      git add .
      git commit -m "[tekton] updating image to $(inputs.params.buildRevision)"
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git push origin $(inputs.resources.source.revision)
---
