apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-system
  name: coffee-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
      - "coffee-shop-prod.cp4multicloud-ibm.com"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istio-system
  name: coffee-gateway
spec:
  hosts:
  - "coffee-shop-prod.cp4multicloud-ibm.com"
  gateways:
  - coffee-gateway
  http:
  - match:
    - uri:
        prefix: "/processes"
    route:
    - destination:
        host: barista.systemtest.svc.cluster.local
        subset: v1
        port:
          number: 8080
  - match:
    - uri:
        prefix: "/orders"
    - uri:
        prefix: "/types"
    - uri:
        prefix: "/health"
    route:
    - destination:
        host: coffee-shop.systemtest.svc.cluster.local
        subset: v1
        port:
          number: 8080
---

