apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-gateway-test
  namespace: istio-system
spec:
  hosts:
  - "coffee-shop-test.cp4multicloud-ibm.com"
  gateways:
  - devready-dashboard-gw
  http:
  - match:
    - uri:
        prefix: "/processes"
    - uri:
        prefix: "/__admin"
    route:
    - destination:
        host: barista.systemtest.svc.cluster.local
        subset: v1
        port:
          number: 8080
  - match:
    - uri:
        prefix: "/orders"
    - uri:
        prefix: "/types"
    - uri:
        prefix: "/health"
    route:
    - destination:
        host: coffee-shop.systemtest.svc.cluster.local
        subset: v1
        port:
          number: 8080
---

