apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-testing
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: production
    repoURL: https://github.com/sdaschner/argocd-testing.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
